import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';
const {JSDOM}=await import(process.env.JSDOM_MODULE||'jsdom');
const dom=new JSDOM('<body><div class="mdl"><div class="player"><iframe src="https://player.vimeo.com/video/123456789"></iframe></div></div></body>',{url:'https://al-ltc.com/',runScripts:'outside-only'});
const w=dom.window;w.__lang='en';let handlers={},instances=0;
w.Vimeo={Player:class{constructor(frame){instances++;this.frame=frame}on(name,fn){handlers[name]=fn}ready(){return Promise.resolve()}destroy(){return Promise.resolve()}}};
w.eval(fs.readFileSync('public/lesson-video.js','utf8'));
const v=w.LessonVideo;
assert.equal(v.storedValue('https://vimeo.com/123456789/abc123'),'123456789?h=abc123');
assert.equal(new URL(v.embedUrl('https://player.vimeo.com/video/123456789?h=abc123')).searchParams.get('h'),'abc123');
assert.equal(v.embedUrl('javascript:alert(1)'),'');assert.equal(v.embedUrl('https://evil.example/123456789'),'');
assert.equal(v.storedValue('123456789'), '123456789');
let ended=0;v.attach(w.document.querySelector('iframe'),()=>ended++);
await new Promise(resolve=>setTimeout(resolve,0));
assert(w.document.querySelector('.mdl').classList.contains('lesson-video-modal'));
assert(w.document.querySelector('.lesson-video-status').hidden);
handlers.ended();assert.equal(ended,1);
handlers.error();assert.equal(w.document.querySelector('.lesson-video-help').hidden,false);
w.document.querySelector('.lesson-video-help button').click();await new Promise(resolve=>setTimeout(resolve,0));
assert.equal(instances,2);assert.equal(w.document.querySelectorAll('iframe').length,1);
assert.equal(w.document.querySelectorAll('.lesson-video-help').length,1);
w.document.querySelector('.mdl').remove();await new Promise(resolve=>setTimeout(resolve,0));dom.window.close();
console.log('PASS: unlisted hashes retained, invalid hosts rejected, ready/error states, same-page retry, completion callback and cleanup.');
